import LocalizedStrings from "react-localization";

export const strings = new LocalizedStrings<ILocalizationStrings>({
  en: {
    apiMethodNotAllowed: `Method not allowed!`,
    defaultLoadingMessage: `Loading...`,
    emptySelectOptionLabel: `-`,
    internalServerErrorMessage: `Looks like something went wrong on our end, we are working hard to fix it! Check back in a few minutes, if the issue persists let an adminstrator know.`,
    noPoliciesFoundMessage: `No policies found`,
    policiesCardsMessage: `Click a card to view more on the policy!`,
    policiesPageDescription: `List of policies`,
    policiesFiltersDriverEmploymentLabel: `Driver employment`,
    policiesFiltersDriverGenderLabel: `Driver gender`,
    policiesFiltersDriverLocationLabel: `Driver location`,
    policiesFiltersDriverMaritalStatusLabel: `Driver marital status`,
    policiesFiltersMonthLabel: `Month`,
    policiesFiltersVehicleModelLabel: `Vehicle model`,
    policiesFiltersYearLabel: `Year`,
    policiesPageTitle: `Policies`,
    policiesTableActionLoadingText: `Updating...`,
    policiesTableDriverAgeColumnTitle: `Driver age`,
    policiesTableDriverGenderColumnTitle: `Driver gender`,
    policiesTableDriverEmploymentColumnTitle: `Driver employment`,
    policiesTableDriverLocationColumnTitle: `Driver location`,
    policiesTableDriverMaritalStatusColumnTitle: `Driver marital status`,
    policiesTableInsuranceClaimsColumnTitle: `Insurance claims`,
    policiesTableInsuranceLossesColumnTitle: `Insurance losses`,
    policiesTableInsurancePremiumColumnTitle: `Insurance premium`,
    policiesTableLoadingMessage: `Getting policies...`,
    policiesTableMessage: `Click a row item to view more on it!`,
    policiesTableMonthColumnTitle: `Month`,
    policiesTableNextActionText: `Next >`,
    policiesTablePageSizeLabelText: `Maximum number of items per page:`,
    policiesTablePreviousActionText: `< Previous`,
    policiesTableVehicleAgeColumnTitle: `Vehicle age (years)`,
    policiesTableVehicleModelColumnTitle: `Vehicle model`,
    policiesTableYearColumnTitle: `Year`,
    policyLoadingMessage: `Getting policy...`,
    policyPageDescription: `Individual policy`,
    policyPageInvalidRowErrorMessage: `Invalid policy row number`,
    policyPageLoadingMessage: `Getting things ready...`,
    policyPageTitle: `Policy {0}`,
  },
});
