import LocalizedStrings from "react-localization";

export const strings = new LocalizedStrings<ILocalizationStrings>({
  en: {
    apiMethodNotAllowed: `Method not allowed!`,
    defaultLoadingMessage: `Loading...`,
    internalServerErrorMessage: `Looks like something went wrong on our end, we are working hard to fix it! Check back in a few minutes, if the issue persists let an adminstrator know.`,
    policiesPageDescription: `List of policies`,
    policiesPageTitle: `Policies`,
    policiesTableDriverAgeColumnTitle: `Driver age`,
    policiesTableDriverGenderColumnTitle: `Driver gender`,
    policiesTableDriverEmploymentColumnTitle: `Driver employment`,
    policiesTableDriverLocationColumnTitle: `Driver location`,
    policiesTableDriverMaritalStatusColumnTitle: `Driver marital status`,
    policiesTableInsuranceClaimsColumnTitle: `Insurance claims`,
    policiesTableInsuranceLossesColumnTitle: `Insurance losses`,
    policiesTableInsurancePremiumColumnTitle: `Insurance premium`,
    policiesTableLoadingMessage: `Getting policies...`,
    policiesTableMonthColumnTitle: `Month`,
    policiesTableNextActionText: `Next ->`,
    policiesTablePageSizeLabelText: `Maximum number of items per page:`,
    policiesTablePreviousActionText: `<- Previous`,
    policiesTableRowColumnTitle: `Row`,
    policiesTableVehicleAgeColumnTitle: `Vehicle age`,
    policiesTableVehicleModelColumnTitle: `Vehicle model`,
    policiesTableYearColumnTitle: `Year`,
    policyLoadingMessage: `Getting policy...`,
    policyPageDescription: `Individual policy`,
    policyPageInvalidRowErrorMessage: `Invalid policy row number`,
    policyPageLoadingMessage: `Getting things ready...`,
    policyPageTitle: `Policy {0}`,
  },
});
